name: Deployment

concurrency:
  group: deployment
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy Services
    uses: ./.github/workflows/template-deploy-cloudrun.yml
    with:
      service_name: hello-world
      gcp_project_id: chuka-wif
      gcp_project_number: 896486946376
      gcp_identity_pool: oidc-pool
      gcp_identity_pool_provider: github
      gcp_service_account_email: wif-513@chuka-wif.iam.gserviceaccount.com
      gcp_gar_repository: hello-world
